name: Close PR environment

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  close_staging_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Close Azure SWA staging environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_TOKEN }}
          action: close
